---
- hosts: all
  gather_facts: no
  become: true
  vars:
    pxe_ip: 10.1.1.1
    dns_domain: test.local
    dhcp_start: 10.1.1.20
    dhcp_end: 10.1.1.30
    category_name: pxetest
    dhcp_hosts:
      pxetestvm:
        mac: "52:11:22:33:44:55"
        ip: "10.1.1.10"
        category: "{{ category_name }}"

  pre_tasks:
    - setup:
      register: pxeserver_setup
      tags:
        - nat_masq
        - pxeserver

    - name: get IP details of pxe interface
      set_fact:
        pxeiface: "{{ pxeserver_setup | iface_details(pxe_ip) }}"
      tags: pxeserver

    - name: set server category
      set_fact:
        server_categories:
          - name: "{{ category_name }}"
            os: xenial
            nic: auto
      tags: pxeserver

    - name: set dhcp pool
      set_fact:
        dhcp_pools: "{{ lookup('template', 'dhcp_pool.j2') | from_yaml }}"
      tags: pxeserver

    - name: get nat masq interface. Its the DHCP interface on the pxeserver VM
      set_fact:
        nat_masq_iface: "{{ pxeserver_setup | iface_details('dhcp') }}"
      tags: nat_masq

  roles:
    - role: pxeserver
      pxe_interface: "{{ pxeiface.device }}"
      tags: pxeserver

    - role: nat_masq
      tags: nat_masq

