---
- assert:
    that: nat_masq_iface is defined

- name: install iptables. Default LXC image doesn't seem to have this
  apt:
    name: iptables

- name: enable ip forwarding
  sysctl:
    name: "net.ipv4.ip_forward"
    value: 1
    sysctl_set: yes
    state: present
    reload: yes

- name: enable NAT masquerading. Add to rc.local
  lineinfile:
    dest: /etc/rc.local
    regexp: "iptables"
    insertbefore: "exit 0"
    line: "/sbin/iptables -t nat -A POSTROUTING -o {{ nat_masq_iface }} -j MASQUERADE"
  notify: run rc.local
